# Generated by Django 2.2.6 on 2019-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20191119_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracaoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
